atlas {
  output.write-mode = "overwrite"
  csv { delimiter = ";"; encoding = "ISO-8859-1" }
  spark { app-name = "atlas-etl"; master = "local[*]"; shuffle-partitions = 64 }
  receita {
    raw-dir = "data/raw/receita/2026-06/estabelecimentos/extracted"
    raw-dir = ${?ATLAS_RECEITA_RAW_DIR}
    bronze-dir = "data/bronze/receita"
    bronze-dir = ${?ATLAS_RECEITA_BRONZE_DIR}
    silver-dir = "data/silver/receita"
    silver-dir = ${?ATLAS_RECEITA_SILVER_DIR}
  }
}
