package atlas.release

import atlas.config.AtlasConfig
import atlas.history.EstablishmentHistoryJob
import atlas.receita.ReceitaIngestJob
import atlas.status.RunStatusRegistry
import java.nio.charset.StandardCharsets
import java.nio.file.{AtomicMoveNotSupportedException, Files, Path, Paths, StandardCopyOption}
import java.time.Instant
import java.time.format.DateTimeFormatter
import org.apache.spark.sql.SparkSession
import scala.collection.JavaConverters._

final case class EstablishmentRebuildPlan(
    fromRelease: ReleaseId,
    toRelease: ReleaseId,
    releases: Seq[ReleaseId],
    missingMonths: Seq[ReleaseId],
    activeBytes: Long,
    usableBytes: Long,
    dryRun: Boolean = true,
    trashRoot: Option[Path] = None
)

object EstablishmentRebuildService {
  private val ReleaseSegment = "([0-9]{4}-[0-9]{2})".r

  def plan(config: AtlasConfig, from: ReleaseId, to: ReleaseId): EstablishmentRebuildPlan = {
    require(from <= to, s"from-release $from must not be newer than to-release $to")
    val discovered = discoverRawReleases(config).filter(release => release >= from && release <= to).sorted
    if (!discovered.contains(from)) throw new IllegalArgumentException(s"Missing raw establishment input for endpoint $from")
    if (!discovered.contains(to)) throw new IllegalArgumentException(s"Missing raw establishment input for endpoint $to")
    val expected = months(from, to)
    val paths = ReleasePaths(config)
    EstablishmentRebuildPlan(
      from,
      to,
      discovered,
      expected.filterNot(discovered.contains),
      activePaths(config).filter(Files.exists(_)).map(size).sum,
      Files.getFileStore(nearestExisting(paths.dataRoot)).getUsableSpace
    )
  }

  def force(
      spark: SparkSession,
      config: AtlasConfig,
      rebuildPlan: EstablishmentRebuildPlan
  ): EstablishmentRebuildPlan = PublicationLock.withEstablishmentsLock(config) {
    recoverInterrupted(config)
    val suffix = java.util.UUID.randomUUID().toString
    val paths = ReleasePaths(config)
    val stagingRoot = paths.atlasRoot.resolve("rebuild-staging").resolve(suffix)
    val stagedConfig = config.copy(
      receita = config.receita.copy(
        bronzeDir = stagingRoot.resolve("bronze/receita").toString,
        silverDir = stagingRoot.resolve("silver/receita").toString
      ),
      statusDir = stagingRoot.resolve("_atlas/status").toString
    )

    try {
      rebuildPlan.releases.foreach { release =>
        val releaseConfig = stagedConfig.copy(receita = stagedConfig.receita.copy(snapshot = release.value))
        ReceitaIngestJob.run(spark, releaseConfig)
        EstablishmentHistoryJob.refresh(spark, releaseConfig)
      }
      canonicalizeStatusPaths(config, stagedConfig)
      deleteIfExists(stagingRoot.resolve("_atlas/work/receita/estabelecimentos"))
      validateStaging(spark, stagedConfig, rebuildPlan)
      val timestamp = DateTimeFormatter.ISO_INSTANT.format(Instant.now()).replace(":", "").replace(".", "")
      val trash = paths.atlasRoot.resolve("_trash").resolve(timestamp).resolve("full-establishments-rebuild")
      promote(config, stagedConfig, stagingRoot, trash)
      rebuildPlan.copy(dryRun = false, trashRoot = Some(trash))
    } catch {
      case error: Throwable =>
        val journal = paths.atlasRoot.resolve("transactions/establishments-rebuild.tsv")
        if (Files.exists(stagingRoot) && !Files.exists(journal)) {
          val timestamp = DateTimeFormatter.ISO_INSTANT.format(Instant.now()).replace(":", "").replace(".", "")
          try move(stagingRoot, paths.atlasRoot.resolve("_trash").resolve(timestamp).resolve("failed-establishments-rebuild").resolve(suffix))
          catch { case cleanup: Throwable => error.addSuppressed(cleanup) }
        }
        throw error
    }
  }

  def render(plan: EstablishmentRebuildPlan): String = {
    val action = if (plan.dryRun) "Dry run" else "Rebuilt"
    val releases = plan.releases.map(_.value).mkString(", ")
    val gaps = if (plan.missingMonths.isEmpty) "none" else plan.missingMonths.map(_.value).mkString(", ")
    val trash = plan.trashRoot.fold("")(path => s"\nPrevious generated data: $path")
    s"$action for Receita establishments ${plan.fromRelease} through ${plan.toRelease}\n" +
      s"Raw releases: $releases\nMissing intermediate months: $gaps\n" +
      s"Active generated bytes: ${plan.activeBytes}\nUsable filesystem bytes: ${plan.usableBytes}\n" +
      "Raw archives and extracted CSV files are protected and are not changed." + trash
  }

  private[release] def discoverRawReleases(config: AtlasConfig): Seq[ReleaseId] = {
    val rawDir = config.receita.rawDir
    val matched = ReleaseSegment.findFirstMatchIn(rawDir).getOrElse(
      throw new IllegalArgumentException(
        "Full rebuild requires a configured raw directory containing a YYYY-MM segment"
      )
    )
    val releasesRoot = Paths.get(rawDir.substring(0, matched.start)).normalize()
    if (!Files.isDirectory(releasesRoot)) return Seq.empty
    val stream = Files.list(releasesRoot)
    try stream.iterator().asScala
      .filter(Files.isDirectory(_))
      .flatMap(path => ReleaseId.parse(path.getFileName.toString).fold(_ => None, Some(_)))
      .filter { release =>
        Files.isDirectory(Paths.get(ReleasePaths.rawDirForRelease(rawDir, release)))
      }
      .toSeq
      .distinct
      .sorted
    finally stream.close()
  }

  private def validateStaging(
      spark: SparkSession,
      stagedConfig: AtlasConfig,
      plan: EstablishmentRebuildPlan
  ): Unit = {
    val finalConfig = stagedConfig.copy(receita = stagedConfig.receita.copy(snapshot = plan.toRelease.value))
    val paths = ReleasePaths(finalConfig)
    val current = spark.read.parquet(paths.silverCurrent.toString)
    val releases = current.select("release").distinct().collect().map(_.getString(0)).toSeq
    if (releases != Seq(plan.toRelease.value))
      throw new IllegalStateException(s"Staged current contains unexpected releases: ${releases.mkString(", ")}")
    val seedHistory = ReleasePaths(
      stagedConfig.copy(receita = stagedConfig.receita.copy(snapshot = plan.fromRelease.value))
    ).historyRelease
    if (Files.exists(seedHistory))
      throw new IllegalStateException(s"Seed release unexpectedly produced history at $seedHistory")
    if (current.groupBy("cnpj_full").count().filter("count > 1").limit(1).count() != 0)
      throw new IllegalStateException("Staged current contains duplicate cnpj_full values")
    plan.releases.sliding(2).foreach {
      case Seq(previous, release) =>
        val eventPath = ReleasePaths(
          stagedConfig.copy(receita = stagedConfig.receita.copy(snapshot = release.value))
        ).historyRelease
        if (Files.exists(eventPath)) {
          val events = spark.read.parquet(eventPath.toString)
          val toReleases = events.select("to_release").distinct().collect().map(_.getString(0)).toSeq
          if (toReleases != Seq(release.value))
            throw new IllegalStateException(s"History partition $eventPath has unexpected to_release values")
          val fromReleases = events.filter("from_release is not null").select("from_release").distinct().collect().map(_.getString(0)).toSeq
          if (fromReleases.exists(_ != previous.value))
            throw new IllegalStateException(s"History partition $eventPath does not follow release $previous")
          if (events.groupBy("event_id").count().filter("count > 1").limit(1).count() != 0)
            throw new IllegalStateException(s"History partition $eventPath contains duplicate event_id values")
        }
      case _ =>
    }
  }

  private def promote(
      config: AtlasConfig,
      stagedConfig: AtlasConfig,
      stagingRoot: Path,
      trash: Path
  ): Unit = {
    val pairs = pathPairs(config, stagedConfig)
    val journal = ReleasePaths(config).atlasRoot.resolve("transactions/establishments-rebuild.tsv")
    Files.createDirectories(journal.getParent)
    val journalLines = Seq(stagingRoot.toString + "\t" + trash.toString) ++ pairs.map {
      case (label, active, staged) =>
        Seq(label, active.toString, staged.toString, trash.resolve(label).toString, Files.exists(active).toString).mkString("\t")
    }
    Files.write(
      journal,
      (journalLines.mkString("\n") + "\n").getBytes(StandardCharsets.UTF_8)
    )
    val moved = scala.collection.mutable.ArrayBuffer.empty[(Path, Path, Path)]
    try {
      pairs.foreach { case (label, active, staged) =>
        val backup = trash.resolve(label)
        if (Files.exists(active)) move(active, backup)
        moved += ((active, staged, backup))
        if (Files.exists(staged)) move(staged, active)
      }
      Files.deleteIfExists(journal)
      deleteIfExists(stagingRoot)
    } catch {
      case error: Throwable =>
        var rollbackFailed = false
        moved.reverse.foreach { case (active, staged, backup) =>
          try {
            if (Files.exists(active)) move(active, staged)
            if (Files.exists(backup)) move(backup, active)
          } catch {
            case rollback: Throwable =>
              rollbackFailed = true
              error.addSuppressed(rollback)
          }
        }
        if (!rollbackFailed) Files.deleteIfExists(journal)
        throw error
    }
  }

  private[release] def recoverInterrupted(config: AtlasConfig): Unit = {
    val journal = ReleasePaths(config).atlasRoot.resolve("transactions/establishments-rebuild.tsv")
    if (Files.exists(journal)) {
      val lines = Files.readAllLines(journal, StandardCharsets.UTF_8).asScala
      if (lines.isEmpty || lines.head.split("\t", -1).length != 2)
        throw new IllegalStateException(s"Malformed establishment rebuild journal requires inspection: $journal")
      val header = lines.head.split("\t", -1)
      val stagingRoot = Paths.get(header(0))
      val trashRoot = Paths.get(header(1))
      lines.drop(1).reverse.foreach { line =>
        val fields = line.split("\t", -1)
        if (fields.length != 5)
          throw new IllegalStateException(s"Malformed establishment rebuild journal requires inspection: $journal")
        val label = fields(0)
        val active = Paths.get(fields(1))
        val staged = Paths.get(fields(2))
        val backup = Paths.get(fields(3))
        val hadActive = fields(4).toBoolean
        if (hadActive && Files.exists(backup)) {
          if (Files.exists(active)) move(active, stagingRoot.resolve("interrupted-promoted").resolve(label))
          move(backup, active)
        } else if (!hadActive && Files.exists(active) && !Files.exists(staged)) {
          move(active, stagingRoot.resolve("interrupted-promoted").resolve(label))
        }
      }
      Files.delete(journal)
      if (Files.exists(stagingRoot)) move(stagingRoot, trashRoot.resolve("interrupted-staging"))
    }
  }

  private def pathPairs(config: AtlasConfig, stagedConfig: AtlasConfig): Seq[(String, Path, Path)] = {
    val active = ReleasePaths(config)
    val staged = ReleasePaths(stagedConfig)
    Seq(
      ("bronze", Paths.get(config.receita.bronzeDir).resolve("estabelecimentos"), Paths.get(stagedConfig.receita.bronzeDir).resolve("estabelecimentos")),
      ("silver-current", active.silverCurrent, staged.silverCurrent),
      ("history", active.historyRoot, staged.historyRoot),
      ("reports", active.atlasRoot.resolve("reports/receita/estabelecimentos"), staged.atlasRoot.resolve("reports/receita/estabelecimentos")),
      ("quality", active.atlasRoot.resolve("quality/receita/establishments"), staged.atlasRoot.resolve("quality/receita/establishments")),
      ("work", active.atlasRoot.resolve("work/receita/estabelecimentos"), staged.atlasRoot.resolve("work/receita/estabelecimentos")),
      ("status-bronze", Paths.get(config.statusDir).resolve("receita/estabelecimentos"), Paths.get(stagedConfig.statusDir).resolve("receita/estabelecimentos")),
      ("status-silver", Paths.get(config.statusDir).resolve("receita/establishments"), Paths.get(stagedConfig.statusDir).resolve("receita/establishments")),
      ("status-history", Paths.get(config.statusDir).resolve("receita/estabelecimentos_history"), Paths.get(stagedConfig.statusDir).resolve("receita/estabelecimentos_history"))
    )
  }

  private def canonicalizeStatusPaths(config: AtlasConfig, stagedConfig: AtlasConfig): Unit = {
    val stagedStatusRoot = Paths.get(stagedConfig.statusDir)
    val scan = RunStatusRegistry.scan(stagedStatusRoot)
    if (scan.errors.nonEmpty) {
      val details = scan.errors.map(error => s"${error.path}: ${error.message}").mkString("; ")
      throw new IllegalStateException(s"Cannot activate malformed staged status metadata: $details")
    }
    val replacements = Seq(
      Paths.get(stagedConfig.receita.bronzeDir) -> Paths.get(config.receita.bronzeDir),
      Paths.get(stagedConfig.receita.silverDir) -> Paths.get(config.receita.silverDir),
      ReleasePaths(stagedConfig).atlasRoot -> ReleasePaths(config).atlasRoot
    )
    scan.statuses.foreach { status =>
      val canonical = status.copy(
        inputPaths = status.inputPaths.map(rewritePath(_, replacements)),
        outputPath = status.outputPath.map(rewritePath(_, replacements)),
        qualityWarnings = status.qualityWarnings.map(warning =>
          warning.copy(reportPath = rewritePath(warning.reportPath, replacements))
        )
      )
      RunStatusRegistry.write(stagedStatusRoot, canonical)
    }
  }

  private def rewritePath(value: String, replacements: Seq[(Path, Path)]): String = {
    replacements.collectFirst {
      case (staged, active) if Paths.get(value).normalize().startsWith(staged.normalize()) =>
        active.normalize().resolve(staged.normalize().relativize(Paths.get(value).normalize())).toString
    }.getOrElse(value)
  }

  private def activePaths(config: AtlasConfig): Seq[Path] = pathPairs(config, config).map(_._2).distinct

  private def months(from: ReleaseId, to: ReleaseId): Seq[ReleaseId] = {
    val start = java.time.YearMonth.parse(from.value)
    val end = java.time.YearMonth.parse(to.value)
    Iterator.iterate(start)(_.plusMonths(1)).takeWhile(!_.isAfter(end)).map(value => ReleaseId.unsafe(value.toString)).toSeq
  }

  private def size(path: Path): Long = {
    val stream = Files.walk(path)
    try stream.iterator().asScala.filter(Files.isRegularFile(_)).map(Files.size(_)).sum
    finally stream.close()
  }

  private def nearestExisting(path: Path): Path =
    Iterator.iterate(path.toAbsolutePath.normalize())(_.getParent).takeWhile(_ != null).find(Files.exists(_)).get

  private def move(source: Path, target: Path): Unit = {
    Option(target.getParent).foreach(Files.createDirectories(_))
    try Files.move(source, target, StandardCopyOption.ATOMIC_MOVE)
    catch {
      case _: AtomicMoveNotSupportedException => Files.move(source, target)
    }
  }

  private def deleteIfExists(path: Path): Unit = {
    if (Files.exists(path)) {
      val stream = Files.walk(path)
      try stream.iterator().asScala.toSeq.sortBy(_.getNameCount).reverse.foreach(Files.deleteIfExists(_))
      finally stream.close()
    }
  }
}
